[2022-08-08 22:01:46,333] {processor.py:163} INFO - Started process (PID=20853) to work on /Users/wangshunda/airflow/dags/comic_app_v2.py
[2022-08-08 22:01:46,334] {processor.py:642} INFO - Processing file /Users/wangshunda/airflow/dags/comic_app_v2.py for tasks to queue
[2022-08-08 22:01:46,335] {logging_mixin.py:109} INFO - [2022-08-08 22:01:46,334] {dagbag.py:500} INFO - Filling up the DagBag from /Users/wangshunda/airflow/dags/comic_app_v2.py
[2022-08-08 22:01:46,446] {logging_mixin.py:109} WARNING - /opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py:188 DeprecationWarning: provide_context is deprecated as of 2.0 and is no longer required
[2022-08-08 22:01:46,450] {logging_mixin.py:109} INFO - [2022-08-08 22:01:46,447] {dagbag.py:334} ERROR - Failed to import: /Users/wangshunda/airflow/dags/comic_app_v2.py
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/wangshunda/airflow/dags/comic_app_v2.py", line 85, in <module>
    token=os.environ['SLACK_BOT_TOKEN'],
  File "/opt/anaconda3/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'SLACK_BOT_TOKEN'
[2022-08-08 22:01:46,477] {processor.py:690} INFO - Deactivated 1 DAGs which are no longer present in /Users/wangshunda/airflow/dags/comic_app_v2.py
[2022-08-08 22:01:46,477] {processor.py:656} WARNING - No viable dags retrieved from /Users/wangshunda/airflow/dags/comic_app_v2.py
[2022-08-08 22:01:46,484] {processor.py:171} INFO - Processing /Users/wangshunda/airflow/dags/comic_app_v2.py took 0.151 seconds
[2022-08-08 22:03:48,187] {processor.py:163} INFO - Started process (PID=21068) to work on /Users/wangshunda/airflow/dags/comic_app_v2.py
[2022-08-08 22:03:48,188] {processor.py:642} INFO - Processing file /Users/wangshunda/airflow/dags/comic_app_v2.py for tasks to queue
[2022-08-08 22:03:48,189] {logging_mixin.py:109} INFO - [2022-08-08 22:03:48,189] {dagbag.py:500} INFO - Filling up the DagBag from /Users/wangshunda/airflow/dags/comic_app_v2.py
[2022-08-08 22:03:49,055] {logging_mixin.py:109} WARNING - /opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py:188 DeprecationWarning: provide_context is deprecated as of 2.0 and is no longer required
[2022-08-08 22:03:49,059] {logging_mixin.py:109} INFO - [2022-08-08 22:03:49,056] {dagbag.py:334} ERROR - Failed to import: /Users/wangshunda/airflow/dags/comic_app_v2.py
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/wangshunda/airflow/dags/comic_app_v2.py", line 85, in <module>
    token=os.environ['SLACK_BOT_TOKEN'],
  File "/opt/anaconda3/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'SLACK_BOT_TOKEN'
[2022-08-08 22:03:49,092] {processor.py:656} WARNING - No viable dags retrieved from /Users/wangshunda/airflow/dags/comic_app_v2.py
[2022-08-08 22:03:49,100] {processor.py:171} INFO - Processing /Users/wangshunda/airflow/dags/comic_app_v2.py took 0.914 seconds
[2022-08-08 22:05:04,445] {processor.py:163} INFO - Started process (PID=21132) to work on /Users/wangshunda/airflow/dags/comic_app_v2.py
[2022-08-08 22:05:04,446] {processor.py:642} INFO - Processing file /Users/wangshunda/airflow/dags/comic_app_v2.py for tasks to queue
[2022-08-08 22:05:04,447] {logging_mixin.py:109} INFO - [2022-08-08 22:05:04,447] {dagbag.py:500} INFO - Filling up the DagBag from /Users/wangshunda/airflow/dags/comic_app_v2.py
[2022-08-08 22:05:04,763] {logging_mixin.py:109} WARNING - /opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py:188 DeprecationWarning: provide_context is deprecated as of 2.0 and is no longer required
[2022-08-08 22:05:04,798] {logging_mixin.py:109} INFO - [2022-08-08 22:05:04,768] {dagbag.py:334} ERROR - Failed to import: /Users/wangshunda/airflow/dags/comic_app_v2.py
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/wangshunda/airflow/dags/comic_app_v2.py", line 85, in <module>
    token=os.environ['SLACK_BOT_TOKEN'],
  File "/opt/anaconda3/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'SLACK_BOT_TOKEN'
[2022-08-08 22:05:05,033] {processor.py:656} WARNING - No viable dags retrieved from /Users/wangshunda/airflow/dags/comic_app_v2.py
[2022-08-08 22:05:05,102] {processor.py:171} INFO - Processing /Users/wangshunda/airflow/dags/comic_app_v2.py took 0.657 seconds
[2022-08-08 22:07:51,945] {processor.py:163} INFO - Started process (PID=21332) to work on /Users/wangshunda/airflow/dags/comic_app_v2.py
[2022-08-08 22:07:51,947] {processor.py:642} INFO - Processing file /Users/wangshunda/airflow/dags/comic_app_v2.py for tasks to queue
[2022-08-08 22:07:51,949] {logging_mixin.py:109} INFO - [2022-08-08 22:07:51,948] {dagbag.py:500} INFO - Filling up the DagBag from /Users/wangshunda/airflow/dags/comic_app_v2.py
[2022-08-08 22:07:52,068] {logging_mixin.py:109} WARNING - /opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/baseoperator.py:188 DeprecationWarning: provide_context is deprecated as of 2.0 and is no longer required
[2022-08-08 22:07:52,073] {logging_mixin.py:109} INFO - [2022-08-08 22:07:52,069] {dagbag.py:334} ERROR - Failed to import: /Users/wangshunda/airflow/dags/comic_app_v2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/wangshunda/airflow/dags/comic_app_v2.py", line 85, in <module>
    token=os.environ['SLACK_BOT_TOKEN'],
  File "/opt/anaconda3/envs/airflow/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'SLACK_BOT_TOKEN'
[2022-08-08 22:07:52,082] {processor.py:656} WARNING - No viable dags retrieved from /Users/wangshunda/airflow/dags/comic_app_v2.py
[2022-08-08 22:07:52,091] {processor.py:171} INFO - Processing /Users/wangshunda/airflow/dags/comic_app_v2.py took 0.150 seconds
